data = [
    {
        'name': 'David Beckham',
        'followers': 62.8,
        'occupation': 'Footballer',
        'country': 'England',
    },
    {
        'name': 'Vin Diesel',
        'followers': 63.9,
        'occupation': 'Actor',
        'country': 'United States of America',
    },
    {
        'name': 'Cardi B',
        'followers': 64.6,
        'occupation': 'Rapper',
        'country': 'United States of America',
    },
    {
        'name': 'Drake',
        'followers': 66.5,
        'occupation': 'Rapper',
        'country': 'United States of America',
    },
    {
        'name': 'Shakira',
        'followers': 66.8,
        'occupation': 'Singer',
        'country': 'Columbia',
    },
    {
        'name': 'Zendaya',
        'followers': 69.1,
        'occupation': 'Actor, Singer',
        'country': 'United States of America',
    },
    {
        'name': 'Demi Lovato',
        'followers': 82,
        'occupation': 'Singer',
        'country': 'United States of America',
    },
    {
        'name': 'Kourtney Kardarshian',
        'followers': 91.9,
        'occupation': 'Model',
        'country': 'United States of America',
    },
    {
        'name': 'Miley Cyrus',
        'followers': 108,
        'occupation': 'Singer, Actor',
        'country': 'United States of America',
    },
    {
        'name': 'Kendall Jenner',
        'followers': 128,
        'occupation': 'Model',
        'country': 'United States of America',
    },
    {
        'name': 'Justin Bieber',
        'followers': 135,
        'occupation': 'Singer',
        'country': 'United States of America',
    },
    {
        'name': 'Neymar',
        'followers': 138,
        'occupation': 'Footballer',
        'country': 'Brazil',
    },
    {
        'name': 'Lionel Messi',
        'followers': 150,
        'occupation': 'Footballer',
        'country': 'Argentina',
    },
    {
        'name': 'Kylie Jenner',
        'followers': 175,
        'occupation': 'Model',
        'country': 'United States of America',
    },
    {
        'name': 'Selena Gomez',
        'followers': 176,
        'occupation': 'Singer',
        'country': 'United States of America',
    },
    {
        'name': 'Cristiano Ronaldo',
        'followers': 218,
        'occupation': 'Footballer',
        'country': 'Portugal',
    },
    {
        'name': 'Brie Larson',
        'followers': 6.7,
        'occupation': 'Actor',
        'country': 'United States of America',
    },
    {
        'name': 'Chadwick Boseman',
        'followers': 11,
        'occupation': 'Actor',
        'country': 'United States of America',
    },
    {
        'name': 'Tom Holland',
        'followers': 45,
        'occupation': 'Footballer',
        'country': 'England',
    },
    {
        'name': 'Chris Hemsworth',
        'followers': 49.6,
        'occupation': 'Actor',
        'country': 'Australia',
    },
    {
        'name': 'Robert Downey Jr',
        'followers': 50.6,
        'occupation': 'Actor',
        'country': 'United States of America',
    },
    {
        'name': 'Virat Kohli',
        'followers': 181.3,
        'occupation': 'Cricketer',
        'country': 'India',
    },
    {
        'name': 'Billie Eilish',
        'followers': 99.4,
        'occupation': 'Singer',
        'country': 'United States of America',
    },
    {
        'name': 'Dua Lipa',
        'followers': 78.1,
        'occupation': 'Singer',
        'country': 'United States of America',
    },
    {
        'name': 'Snopp Dogg',
        'followers': 67.1,
        'occupation': 'Rapper',
        'country': 'United States of America',
    },
    {
        'name': 'Shawn Mendes',
        'followers': 66.3,
        'occupation': 'Singer',
        'country': 'United States of America',
    },
    {
        'name': 'Will Smith',
        'followers': 56.5,
        'occupation': 'Actor',
        'country': 'United States of America',
    },
    {
        'name': 'Leonardo DiCaprio',
        'followers': 52.1,
        'occupation': 'Actor',
        'country': 'United States of America',
    },
    {
        'name': 'Gigi Hadid',
        'followers': 72.1,
        'occupation': 'Model',
        'country': 'United States of America',
    },
    {
        'name': 'Charli D Amelio',
        'followers': 46.7,
        'occupation': 'Tiktoker',
        'country': 'United States of America',
    },
]